### ISSUE TITLE
'number' pattern invalid if decimal

### ISSUE THREAD

**Issue by neptunian** [thedersen/backbone.validation#286]
I'm using the built in 'number' pattern to validate for numeric input.  Is it correct that something like '.234' is considered non numeric?

**Comment by platinumazure** [comment]
Is this covered by issue #103 and/or pull request #230?

If so, it looks like we do have a fix proposed; it's just not mergeable at this point. If I get a chance, I can try to recreate the pull request from my own repository since there isn't much activity on the other one.

@chiefGui If @neptunian agrees, do you want to close this as a duplicate of #103?

**Comment by neptunian** [comment]
Thanks @platinumazure
