### ISSUE TITLE
can't use forceUpdate:true and model.validate() together?

### ISSUE THREAD

**Issue by JasonMore** [thedersen/backbone.validation#46]
Hi, 

I was wondering why you have this bit of code in the validation:

```
            if (!opt.forceUpdate && result.errorMessages.length > 0) {
                return result;
            }
```

The way I see it, you can't manually call model.validate() and get anything back when forceUpdate:true. It will always be undefined.

**Comment by clintonb** [comment]
@thedersen Is there a method that returns the fields that are invalid? `model.isValid(true)` only returns a boolean and, as mentioned, `model.validate()` always returns `undefined`.

**Comment by chiefGui** [comment]
@clintonb 

> Backbone provides a validate method, but it is left undefined and it is up to you to override it with your custom validation logic.

**Comment by clintonb** [comment]
@chiefGui I am aware of that; however, when not using `forceUpdate`, `Backbone.Validation` provides a `validate` method that does what I would like  (check each field and return an appropriate error message). I would like to be able to use this method in conjunction with `forceUpdate`.

**Comment by fredgate** [comment]
> If validate returns something, Backbone will not update the model. There's no other way to get Backbone to update the model with invalid values. 

This is not exact, at least since Backbone 1.0.0.
Backbone.Model.set validates the model and returns if the model is invalid. But an option can be passed to skip the validation and so the attributes are always set.

```
model.set({foo:'bar'}, {validate: false})
```

Does Backbone.validation should not always return the errors (invalid attributes), and the usage of forceUpdate deprecated ? What do you think ?
